// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfsx6YLdO7HL2rWviXcCge4-VtPHF8HS4',
    appId: '1:647251551994:web:06d37b871c84733486cb43',
    messagingSenderId: '647251551994',
    projectId: 'nomad-3daff',
    authDomain: 'nomad-3daff.firebaseapp.com',
    storageBucket: 'nomad-3daff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7rulRH7LrrdCIHusXfTEddsbFFMUg7pg',
    appId: '1:647251551994:android:efd69425a682412386cb43',
    messagingSenderId: '647251551994',
    projectId: 'nomad-3daff',
    storageBucket: 'nomad-3daff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtEMxCwt9tQQBAPAFtusRDbnczabBM-dw',
    appId: '1:647251551994:ios:dc1d461d4786743986cb43',
    messagingSenderId: '647251551994',
    projectId: 'nomad-3daff',
    storageBucket: 'nomad-3daff.firebasestorage.app',
    androidClientId: '647251551994-07c6eibqv2avfmm8ib8q37d05ii72ck1.apps.googleusercontent.com',
    iosClientId: '647251551994-prn78fgpdihju3oq69k6umtevpvckrb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cercaDeCasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtEMxCwt9tQQBAPAFtusRDbnczabBM-dw',
    appId: '1:647251551994:ios:dc1d461d4786743986cb43',
    messagingSenderId: '647251551994',
    projectId: 'nomad-3daff',
    storageBucket: 'nomad-3daff.firebasestorage.app',
    androidClientId: '647251551994-07c6eibqv2avfmm8ib8q37d05ii72ck1.apps.googleusercontent.com',
    iosClientId: '647251551994-prn78fgpdihju3oq69k6umtevpvckrb7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cercaDeCasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfsx6YLdO7HL2rWviXcCge4-VtPHF8HS4',
    appId: '1:647251551994:web:7012ed9d54ed872a86cb43',
    messagingSenderId: '647251551994',
    projectId: 'nomad-3daff',
    authDomain: 'nomad-3daff.firebaseapp.com',
    storageBucket: 'nomad-3daff.firebasestorage.app',
  );

}